knp_paginator:
  page_range: 5 # Nombre de pages affichées autour de la page courante
  default_options:
    page_name: page # Nom du paramètre pour la page courante
    sort_field_name: sort  # Nom du paramètre pour le tri
    sort_direction_name: direction # Nom du paramètre pour la direction du tri
    distinct: true     # Pour les jointures pour éviter les doublons
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Le template pour Bootstrap 5
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
