parameters:
  upload_directory: "%kernel.project_dir%/public/uploads/documents"
  images_directory: "%kernel.project_dir%/public/images"
  google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
  google_recaptcha_secret_key: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Twig\AppExtension:
    tags:
      - { name: twig.extension }

  App\:
    resource: "../src/*"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Tests/"

  App\Security\UserValidationChecker:
    arguments:
      $session: '@Symfony\Component\HttpFoundation\Session\SessionInterface'
    tags:
      - { name: "security.user_checker" }

  Symfony\Component\HttpFoundation\Session\SessionInterface:
    class: Symfony\Component\HttpFoundation\Session\Session

  App\Security\LoginFormAuthenticator:
    arguments:
      $userChecker: "@security.user_checker" # Utilisez le service par défaut

  App\Service\RecaptchaValidator:
    arguments:
      $secretKey: '%google_recaptcha_secret_key%'

twig:
  globals:
    current_route: '@request_stack'