parameters:
  upload_directory: "%kernel.project_dir%/public/uploads/documents"
  images_directory: "%kernel.project_dir%/public/images"

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Twig\AppExtension:
    tags:
      - { name: twig.extension }

  App\:
    resource: "../src/*"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Tests/"
  App\Security\UserValidationChecker:
    arguments:
      $session: '@Symfony\Component\HttpFoundation\Session\SessionInterface'

  Symfony\Component\HttpFoundation\Session\SessionInterface:
    class: Symfony\Component\HttpFoundation\Session\Session
